apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/nginx
nameSuffix: "-dev"
namespace: web-dev
patches:
  - target:
      kind: HelmRelease
      name: nginx-dev
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: nginx-dev
        namespace: web-dev
      spec:
        values:
          replicaCount: 1
